--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2023-06-23 18:28:19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA auth;


ALTER SCHEMA auth OWNER TO postgres;

--
-- TOC entry 7 (class 2615 OID 16546)
-- Name: sys; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA sys;


ALTER SCHEMA sys OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16547)
-- Name: nodos; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth.nodos (
    id integer NOT NULL,
    ip character varying,
    puerto integer
);


ALTER TABLE auth.nodos OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16552)
-- Name: nodos_id_seq; Type: SEQUENCE; Schema: auth; Owner: postgres
--

ALTER TABLE auth.nodos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.nodos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16553)
-- Name: usuarios; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth.usuarios (
    id integer NOT NULL,
    nombre character varying NOT NULL,
    isadmin boolean DEFAULT false NOT NULL
);


ALTER TABLE auth.usuarios OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16559)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: auth; Owner: postgres
--

ALTER TABLE auth.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16560)
-- Name: areas; Type: TABLE; Schema: sys; Owner: postgres
--

CREATE TABLE sys.areas (
    id integer NOT NULL,
    nombre character varying NOT NULL,
    replicas integer DEFAULT 1 NOT NULL
);


ALTER TABLE sys.areas OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16566)
-- Name: areas_id_seq; Type: SEQUENCE; Schema: sys; Owner: postgres
--

ALTER TABLE sys.areas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sys.areas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 99999999
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16567)
-- Name: asignaciones; Type: TABLE; Schema: sys; Owner: postgres
--

CREATE TABLE sys.asignaciones (
    nodoid integer NOT NULL,
    areaid integer NOT NULL
);


ALTER TABLE sys.asignaciones OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16570)
-- Name: noticias; Type: TABLE; Schema: sys; Owner: postgres
--

CREATE TABLE sys.noticias (
    id integer NOT NULL,
    areaid integer NOT NULL,
    authorid integer NOT NULL,
    fecha timestamp with time zone NOT NULL,
    texto character varying NOT NULL
);


ALTER TABLE sys.noticias OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16575)
-- Name: noticias_id_seq; Type: SEQUENCE; Schema: sys; Owner: postgres
--

ALTER TABLE sys.noticias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sys.noticias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999999
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16576)
-- Name: suscripciones; Type: TABLE; Schema: sys; Owner: postgres
--

CREATE TABLE sys.suscripciones (
    usuarioid integer NOT NULL,
    areaid integer NOT NULL
);


ALTER TABLE sys.suscripciones OWNER TO postgres;

--
-- TOC entry 3356 (class 0 OID 16547)
-- Dependencies: 216
-- Data for Name: nodos; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth.nodos (id, ip, puerto) FROM stdin;
\.


--
-- TOC entry 3358 (class 0 OID 16553)
-- Dependencies: 218
-- Data for Name: usuarios; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth.usuarios (id, nombre, isadmin) FROM stdin;
6	Albano	f
7	Franco	f
8	Nicolas	f
1	Admin	t
2	Usuario	f
3	Agustin	f
\.


--
-- TOC entry 3360 (class 0 OID 16560)
-- Dependencies: 220
-- Data for Name: areas; Type: TABLE DATA; Schema: sys; Owner: postgres
--

COPY sys.areas (id, nombre, replicas) FROM stdin;
1	Deportivas	3
2	Politicas	1
3	Sociales	1
4	Del Mundo	1
5	Economicas	1
\.


--
-- TOC entry 3362 (class 0 OID 16567)
-- Dependencies: 222
-- Data for Name: asignaciones; Type: TABLE DATA; Schema: sys; Owner: postgres
--

COPY sys.asignaciones (nodoid, areaid) FROM stdin;
\.


--
-- TOC entry 3363 (class 0 OID 16570)
-- Dependencies: 223
-- Data for Name: noticias; Type: TABLE DATA; Schema: sys; Owner: postgres
--

COPY sys.noticias (id, areaid, authorid, fecha, texto) FROM stdin;
\.


--
-- TOC entry 3365 (class 0 OID 16576)
-- Dependencies: 225
-- Data for Name: suscripciones; Type: TABLE DATA; Schema: sys; Owner: postgres
--

COPY sys.suscripciones (usuarioid, areaid) FROM stdin;
\.


--
-- TOC entry 3371 (class 0 OID 0)
-- Dependencies: 217
-- Name: nodos_id_seq; Type: SEQUENCE SET; Schema: auth; Owner: postgres
--

SELECT pg_catalog.setval('auth.nodos_id_seq', 94, true);


--
-- TOC entry 3372 (class 0 OID 0)
-- Dependencies: 219
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: auth; Owner: postgres
--

SELECT pg_catalog.setval('auth.usuarios_id_seq', 8, true);


--
-- TOC entry 3373 (class 0 OID 0)
-- Dependencies: 221
-- Name: areas_id_seq; Type: SEQUENCE SET; Schema: sys; Owner: postgres
--

SELECT pg_catalog.setval('sys.areas_id_seq', 8, true);


--
-- TOC entry 3374 (class 0 OID 0)
-- Dependencies: 224
-- Name: noticias_id_seq; Type: SEQUENCE SET; Schema: sys; Owner: postgres
--

SELECT pg_catalog.setval('sys.noticias_id_seq', 9, true);


--
-- TOC entry 3201 (class 2606 OID 16580)
-- Name: nodos nodos_pk; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth.nodos
    ADD CONSTRAINT nodos_pk PRIMARY KEY (id);


--
-- TOC entry 3203 (class 2606 OID 16582)
-- Name: usuarios usuarios_pk; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth.usuarios
    ADD CONSTRAINT usuarios_pk PRIMARY KEY (id);


--
-- TOC entry 3205 (class 2606 OID 16584)
-- Name: areas areas_pk; Type: CONSTRAINT; Schema: sys; Owner: postgres
--

ALTER TABLE ONLY sys.areas
    ADD CONSTRAINT areas_pk PRIMARY KEY (id);


--
-- TOC entry 3207 (class 2606 OID 16586)
-- Name: noticias noticias_pk; Type: CONSTRAINT; Schema: sys; Owner: postgres
--

ALTER TABLE ONLY sys.noticias
    ADD CONSTRAINT noticias_pk PRIMARY KEY (id);


--
-- TOC entry 3208 (class 2606 OID 16587)
-- Name: asignaciones asignaciones_fk; Type: FK CONSTRAINT; Schema: sys; Owner: postgres
--

ALTER TABLE ONLY sys.asignaciones
    ADD CONSTRAINT asignaciones_fk FOREIGN KEY (areaid) REFERENCES sys.areas(id) ON DELETE CASCADE;


--
-- TOC entry 3209 (class 2606 OID 16592)
-- Name: asignaciones asignaciones_fk_1; Type: FK CONSTRAINT; Schema: sys; Owner: postgres
--

ALTER TABLE ONLY sys.asignaciones
    ADD CONSTRAINT asignaciones_fk_1 FOREIGN KEY (nodoid) REFERENCES auth.nodos(id) ON DELETE CASCADE;


--
-- TOC entry 3210 (class 2606 OID 16597)
-- Name: noticias noticias_fk; Type: FK CONSTRAINT; Schema: sys; Owner: postgres
--

ALTER TABLE ONLY sys.noticias
    ADD CONSTRAINT noticias_fk FOREIGN KEY (areaid) REFERENCES sys.areas(id);


--
-- TOC entry 3211 (class 2606 OID 16602)
-- Name: noticias noticias_fk_1; Type: FK CONSTRAINT; Schema: sys; Owner: postgres
--

ALTER TABLE ONLY sys.noticias
    ADD CONSTRAINT noticias_fk_1 FOREIGN KEY (authorid) REFERENCES auth.usuarios(id);


--
-- TOC entry 3212 (class 2606 OID 16607)
-- Name: suscripciones suscripciones_fk; Type: FK CONSTRAINT; Schema: sys; Owner: postgres
--

ALTER TABLE ONLY sys.suscripciones
    ADD CONSTRAINT suscripciones_fk FOREIGN KEY (areaid) REFERENCES sys.areas(id) ON DELETE CASCADE;


--
-- TOC entry 3213 (class 2606 OID 16612)
-- Name: suscripciones suscripciones_fk_2; Type: FK CONSTRAINT; Schema: sys; Owner: postgres
--

ALTER TABLE ONLY sys.suscripciones
    ADD CONSTRAINT suscripciones_fk_2 FOREIGN KEY (usuarioid) REFERENCES auth.usuarios(id) ON DELETE CASCADE;


-- Completed on 2023-06-23 18:28:19

--
-- PostgreSQL database dump complete
--

